### ISSUE TITLE
Google screencaps are outdated in documentation

### ISSUE THREAD

**Issue by ryanbmarx** [tarbell-project/tarbell#396] opened 2016-01-20 17:50 UTC
The otherwise very helpful docs show pretty old screencaps from the Google Dev console. Users unfamiliar with that system might get turned around pretty quick trying to generate a client_secrets file.

**Comment by ghing** [comment] 2016-01-21 22:09
@ryanbmarx This is a duplicate of #393.  I'm going to close this and continue this discussion there.

**Closed by ghing** 2016-01-21 22:09 UTC
